# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c0b5597ac1191d93f170319baae830ab5f39b7e41c0ef092c306fa09d63d08d6d2e7ba2058556326fd3fd59c0932374adf7720275ffeedc4f90e6e2ada940d3

test:
  secret_key_base: f845d8ced78aae33e09c2c3445786c574be29df3426213dc081e796d522e665ee05a8c381f3efa46055980d638a58e291c780415377753b0dd86349e9370acc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
